name: Docker Publish
on:
  repository_dispatch:
    types: [docker_build]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cie.js
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.SUB_MODULE_TOKEN }}
          submodules: true
      - name: Update submodule
        run: git submodule update --remote ./libs/
      - name: CIE.sh version check
        run: ./libs/CIE.sh/bin/lab -v
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get latest version tag
        id: latest_tag
        run: |
          tag="$(grep version <package.json | cut -d ' ' -f 4 | tr -d ',' | tr -d \")"
          echo "::set-output name=tag::${tag}"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.latest_tag.outputs.tag }}