name: Labeler
on:
  pull_request:
    branches:
      - master

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Labeling of "automerge"
      if: ${{ github.actor }} == ${{ github.repository_owner }}
      uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"