name: Npm Publish
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.SUB_MODULE_TOKEN }}
          submodules: true
      - name: Update submodule
        run: git submodule update --remote ./libs/
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org/"
      - name: CIE.sh version check
        run: ./libs/CIE.sh/bin/lab -v 
      - name: Check version and Add Tag
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          COMMIT: ${{ github.sha }}
      - name: Run Test
        run: yarn test:coverage
      - name: Run Build
        run: yarn build
      - name: Run Release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Release Data Extract
        id: release_data
        run: |
          git pull
          body=$(git log --pretty=format:"%s" $(git tag --sort=-v:refname -l '[0-9]*.[0-9]*.[0-9]*'|tr "\n" " "|sed "s/ /.../;s/ $//")|cat -)
          tag_name=$(git describe)
          release_name=$(git describe)
          echo "::set-output name=tag_name::${tag_name}"
          echo "::set-output name=release_name::${release_name}"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_data.outputs.tag_name }}
          release_name: ${{ steps.release_data.outputs.release_name }}
          body: ${{ steps.release_data.outputs.body }}
          draft: false
          prerelease: false
      - name: Start Document Publish
        uses: juztcode/repo-ditpatch-action@v1
        with:
          event-type: document
          token: ${{ secrets.DOCUMENT_PUBLISH }}
          repository: redpeacock78/cie.js
      - name: Start Docker image build
        uses: juztcode/repo-ditpatch-action@v1
        with:
          event-type: docker_build
          token: ${{ secrets.DOCKER_PUBLISH }}
          repository: redpeacock78/cie.js